
production:
    adapter: mysql2
    encoding: utf8
    database: shapd_production
    username: root
    password: 123shapdmysql
    host: 127.0.0.1
    socket: /tmp/mysql.sock

development:
    adapter: mysql2
    encoding: utf8
    database: shapd_devel
    username: root
    password: 123shapdmysql
    host: 127.0.0.1
    socket: /tmp/mysql.sock

test:
    adapter: mysql2
    encoding: utf8
    database: shapd_test
    username: root
    password: 123shapdmysql
    host: 127.0.0.1
    socket: /tmp/mysql.sock

