
production:
    adapter: mysql2
    encoding: utf8
    database: shapd_production
    username: root
    password: 123shapdmysql
    host: shapd2.cxu180ipkbub.us-west-2.rds.amazonaws.com
    port: 3306
    socket: /tmp/mysql.sock

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
    adapter: mysql2
    encoding: utf8
    database: shapd_test
    username: root
    password: 123shapdmysql
    host: 127.0.0.1
    socket: /tmp/mysql.sock

