
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
    adapter: mysql2
    encoding: utf8
    database: shapd_test
    username: root
    password: 123shapdmysql
    host: 127.0.0.1
    socket: /tmp/mysql.sock

